# _______________________________________
# Help plugin for MCPE 0.14.3 x 0.15.10
# By: Luiz Guilherme (frpitu)
# Github: https://github.com/frpitu
# Twitter: https://twitter.com/frpitu
# Discord: frpitu#1085 | frpitu
# ________________________________________
message: 